image: python:2.7

before_script:
  - pip install --upgrade setuptools pip

stages:
  - build
  - test

install-requirements:
  stage: build
  script:
    - pip install -r requirements_dev.txt

test:
  script:
    - nosetests
